/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        secondary: '#8d4f11',
        'surface-container': '#f0eded',
        'on-tertiary': '#ffffff',
        'on-primary-fixed-variant': '#920023',
        'tertiary-fixed': '#c0f0ad',
        'secondary-container': '#feac67',
        'on-error': '#ffffff',
        'surface-tint': '#ba1434',
        'surface-bright': '#fcf9f8',
        error: '#ba1a1a',
        'on-secondary-fixed': '#2f1500',
        'on-primary-fixed': '#40000a',
        'outline-variant': '#e3bebd',
        'on-tertiary-container': '#c0f0ad',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#ffb3b4',
        'on-secondary-container': '#773e00',
        'secondary-fixed-dim': '#ffb77d',
        'tertiary-container': '#466f39',
        'on-primary': '#ffffff',
        tertiary: '#2e5624',
        'on-tertiary-fixed-variant': '#28501e',
        'inverse-on-surface': '#f3f0f0',
        'on-primary-container': '#ffdada',
        'primary-container': '#c41e3a',
        'surface-container-high': '#eae7e7',
        'on-secondary-fixed-variant': '#6e3900',
        'tertiary-fixed-dim': '#a4d393',
        outline: '#8f6f6f',
        'surface-container-low': '#f6f3f2',
        'error-container': '#ffdad6',
        'surface-variant': '#e4e2e1',
        primary: '#9e0027',
        'primary-fixed': '#ffdad9',
        'on-tertiary-fixed': '#022100',
        background: '#fcf9f8',
        'secondary-fixed': '#ffdcc3',
        'surface-dim': '#dcd9d9',
        'on-error-container': '#93000a',
        'on-surface-variant': '#5b4040',
        'inverse-surface': '#303030',
        surface: '#fcf9f8',
        'surface-container-lowest': '#ffffff',
        'inverse-primary': '#ffb3b4',
        'surface-container-highest': '#e4e2e1',
        'on-background': '#1b1c1c',
        'on-surface': '#1b1c1c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '40px',
        'margin-mobile': '16px',
        gutter: '24px',
        'container-max': '1280px',
      },
      maxWidth: {
        sm: '24rem',
        md: '28rem',
        lg: '32rem',
        xl: '36rem',
        '2xl': '42rem',
        'container-max': '1280px',
      },
      fontFamily: {
        epilogue: ['Epilogue', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        'display-lg': ['Epilogue', 'sans-serif'],
        'display-lg-mobile': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'headline-sm': ['Epilogue', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['36px', { lineHeight: '42px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      boxShadow: {
        'level-1': '0px 4px 12px rgba(45, 45, 45, 0.05)',
        'level-2': '0px 12px 24px rgba(45, 45, 45, 0.12)',
        'nav-top': '0 4px 12px rgba(45, 45, 45, 0.05)',
        'nav-bottom': '0 -4px 12px rgba(45, 45, 45, 0.05)',
      },
    },
  },
  plugins: [],
}
